# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mt5bridge_pb2 as mt5bridge__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mt5bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MT5BridgeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/mt5bridge.MT5Bridge/Health',
                request_serializer=mt5bridge__pb2.Empty.SerializeToString,
                response_deserializer=mt5bridge__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/mt5bridge.MT5Bridge/GetAccount',
                request_serializer=mt5bridge__pb2.Empty.SerializeToString,
                response_deserializer=mt5bridge__pb2.Account.FromString,
                _registered_method=True)
        self.GetTick = channel.unary_unary(
                '/mt5bridge.MT5Bridge/GetTick',
                request_serializer=mt5bridge__pb2.SymbolRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.Tick.FromString,
                _registered_method=True)
        self.GetRates = channel.unary_unary(
                '/mt5bridge.MT5Bridge/GetRates',
                request_serializer=mt5bridge__pb2.RatesRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.RatesReply.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/mt5bridge.MT5Bridge/GetPositions',
                request_serializer=mt5bridge__pb2.PositionsRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.PositionsReply.FromString,
                _registered_method=True)
        self.GetPendingOrders = channel.unary_unary(
                '/mt5bridge.MT5Bridge/GetPendingOrders',
                request_serializer=mt5bridge__pb2.PositionsRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.PendingOrdersReply.FromString,
                _registered_method=True)
        self.MarketOrder = channel.unary_unary(
                '/mt5bridge.MT5Bridge/MarketOrder',
                request_serializer=mt5bridge__pb2.MarketOrderRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.TradeResult.FromString,
                _registered_method=True)
        self.SendOrder = channel.unary_unary(
                '/mt5bridge.MT5Bridge/SendOrder',
                request_serializer=mt5bridge__pb2.TradeRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.TradeResult.FromString,
                _registered_method=True)
        self.CheckOrder = channel.unary_unary(
                '/mt5bridge.MT5Bridge/CheckOrder',
                request_serializer=mt5bridge__pb2.TradeRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.CheckResult.FromString,
                _registered_method=True)
        self.ClosePosition = channel.unary_unary(
                '/mt5bridge.MT5Bridge/ClosePosition',
                request_serializer=mt5bridge__pb2.CloseRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.TradeResult.FromString,
                _registered_method=True)
        self.StreamTicks = channel.unary_stream(
                '/mt5bridge.MT5Bridge/StreamTicks',
                request_serializer=mt5bridge__pb2.StreamTicksRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.Tick.FromString,
                _registered_method=True)
        self.StreamAccount = channel.unary_stream(
                '/mt5bridge.MT5Bridge/StreamAccount',
                request_serializer=mt5bridge__pb2.StreamAccountRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.Account.FromString,
                _registered_method=True)
        self.StreamPositions = channel.unary_stream(
                '/mt5bridge.MT5Bridge/StreamPositions',
                request_serializer=mt5bridge__pb2.StreamPositionsRequest.SerializeToString,
                response_deserializer=mt5bridge__pb2.PositionsReply.FromString,
                _registered_method=True)


class MT5BridgeServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarketOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClosePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MT5BridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mt5bridge__pb2.Empty.FromString,
                    response_serializer=mt5bridge__pb2.HealthReply.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=mt5bridge__pb2.Empty.FromString,
                    response_serializer=mt5bridge__pb2.Account.SerializeToString,
            ),
            'GetTick': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTick,
                    request_deserializer=mt5bridge__pb2.SymbolRequest.FromString,
                    response_serializer=mt5bridge__pb2.Tick.SerializeToString,
            ),
            'GetRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRates,
                    request_deserializer=mt5bridge__pb2.RatesRequest.FromString,
                    response_serializer=mt5bridge__pb2.RatesReply.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=mt5bridge__pb2.PositionsRequest.FromString,
                    response_serializer=mt5bridge__pb2.PositionsReply.SerializeToString,
            ),
            'GetPendingOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingOrders,
                    request_deserializer=mt5bridge__pb2.PositionsRequest.FromString,
                    response_serializer=mt5bridge__pb2.PendingOrdersReply.SerializeToString,
            ),
            'MarketOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.MarketOrder,
                    request_deserializer=mt5bridge__pb2.MarketOrderRequest.FromString,
                    response_serializer=mt5bridge__pb2.TradeResult.SerializeToString,
            ),
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=mt5bridge__pb2.TradeRequest.FromString,
                    response_serializer=mt5bridge__pb2.TradeResult.SerializeToString,
            ),
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=mt5bridge__pb2.TradeRequest.FromString,
                    response_serializer=mt5bridge__pb2.CheckResult.SerializeToString,
            ),
            'ClosePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ClosePosition,
                    request_deserializer=mt5bridge__pb2.CloseRequest.FromString,
                    response_serializer=mt5bridge__pb2.TradeResult.SerializeToString,
            ),
            'StreamTicks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTicks,
                    request_deserializer=mt5bridge__pb2.StreamTicksRequest.FromString,
                    response_serializer=mt5bridge__pb2.Tick.SerializeToString,
            ),
            'StreamAccount': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAccount,
                    request_deserializer=mt5bridge__pb2.StreamAccountRequest.FromString,
                    response_serializer=mt5bridge__pb2.Account.SerializeToString,
            ),
            'StreamPositions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPositions,
                    request_deserializer=mt5bridge__pb2.StreamPositionsRequest.FromString,
                    response_serializer=mt5bridge__pb2.PositionsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5bridge.MT5Bridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mt5bridge.MT5Bridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MT5Bridge:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/Health',
            mt5bridge__pb2.Empty.SerializeToString,
            mt5bridge__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/GetAccount',
            mt5bridge__pb2.Empty.SerializeToString,
            mt5bridge__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/GetTick',
            mt5bridge__pb2.SymbolRequest.SerializeToString,
            mt5bridge__pb2.Tick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/GetRates',
            mt5bridge__pb2.RatesRequest.SerializeToString,
            mt5bridge__pb2.RatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/GetPositions',
            mt5bridge__pb2.PositionsRequest.SerializeToString,
            mt5bridge__pb2.PositionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/GetPendingOrders',
            mt5bridge__pb2.PositionsRequest.SerializeToString,
            mt5bridge__pb2.PendingOrdersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarketOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/MarketOrder',
            mt5bridge__pb2.MarketOrderRequest.SerializeToString,
            mt5bridge__pb2.TradeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/SendOrder',
            mt5bridge__pb2.TradeRequest.SerializeToString,
            mt5bridge__pb2.TradeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/CheckOrder',
            mt5bridge__pb2.TradeRequest.SerializeToString,
            mt5bridge__pb2.CheckResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClosePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5bridge.MT5Bridge/ClosePosition',
            mt5bridge__pb2.CloseRequest.SerializeToString,
            mt5bridge__pb2.TradeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mt5bridge.MT5Bridge/StreamTicks',
            mt5bridge__pb2.StreamTicksRequest.SerializeToString,
            mt5bridge__pb2.Tick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mt5bridge.MT5Bridge/StreamAccount',
            mt5bridge__pb2.StreamAccountRequest.SerializeToString,
            mt5bridge__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mt5bridge.MT5Bridge/StreamPositions',
            mt5bridge__pb2.StreamPositionsRequest.SerializeToString,
            mt5bridge__pb2.PositionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
